services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432
    environment:
      - POSTGRES_DB=initialDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - docker_services_network

networks:
  docker_services_network:
    name: docker_services_network
    external: true
