services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432
    environment:
      - POSTGRES_DB=initialDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"  # Map container port 80 to host port 5050
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@sonu.info
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    networks:
      - pg_network

networks:
  pg_network:
