services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - ./html:/var/www/html
    networks:
      - docker_services_network

  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: initialDB
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - docker_services_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "5051:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    networks:
      - docker_services_network

networks:
  docker_services_network:
    external:
      name: docker_services_network