services:

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"  # Map container port 80 to host port 5050
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@sonu.info
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    networks:
      - docker_services_network

networks:
  docker_services_network:
    external:
      name: docker_services_network
